---
# Note: to override this add overrides to the node file in host_vars/

# NREC vars
foreman_repo_server: "https://download.iaas.uio.no/nrec/{{ repo_env }}"

# Foreman global settings
foreman_server_url: "https://foreman.{{ domain_mgmt }}"
foreman_username: 'admin'
foreman_password: 'changeme'
foreman_validate_certs: no

# Foreman: global parameter
foreman_global_parameter:
   - name:  'time-zone'
     value: 'Europe/Oslo'
   - name:  'ntp-server'
     value: 'no.pool.ntp.org'
#  - keyboard:
#    value: 'no'
#  - selinux-mode:
#    value: 'permissive'
#  - run-puppet-in-installer:
#    value: true
#    parameter_type: boolean
#  - lang:
#    value: 'en_US'
#  - enable-puppetlabs-puppet5-repo:
#    value: false
#    parameter_type: boolean
#  - enable-puppetlabs-puppet6-repo:
#    value: true

# Foreman: template sync
foreman_template_repo:   'https://github.com/norcams/foreman-templates.git'
foreman_template_branch: 'master'
foreman_template_prefix: 'norcams-'
foreman_template_associate: always

# Installation medium
foreman_installation_medium:
  - name: "CentOS NREC mirror"
    path: "{{ foreman_repo_server }}/el7/centos-base"
    os_family: "Redhat"
  - name: "AlmaLinux NREC mirror"
    path: "{{ foreman_repo_server }}/el8/almalinux-base"
    os_family: "Redhat"

# Use hieradata for foreman settings for now
foreman_settings: []

# Foreman: domains
foreman_domains:
  - name: "{{ domain_mgmt }}"

# Foreman: subnet
foreman_subnets:
  - name: "{{ location }}"
    description: "mgmt net"
    network: "{{ ansible_facts[mgmt_interface]['ipv4']['network'] }}"
    cidr: "{{ ansible_facts[mgmt_interface]['ipv4']['prefix'] }}"
    mask: "{{ ansible_facts[mgmt_interface]['ipv4']['netmask'] }}"
    gateway: "{{ foreman_subnet_gateway | default(omit) }}"
    dns_primary: "{{ foreman_dns_primary | default(ansible_facts['dns']['nameservers'][0]) }}"
      #    from_ip: "{{ mgmt_network_cidr | ansible.utils.ipaddr(dhcp_pool_start | mandatory ) | ansible.utils.ipaddr('address') }}"
      #    to_ip: "{{  mgmt_network_cidr | ansible.utils.ipaddr(dhcp_pool_end) | ansible.utils.ipaddr('address') }}"
    boot_mode: "DHCP"
    dhcp_proxy: "{{ foreman_dhcp_proxy | default(ansible_fqdn) }}"
    tftp_proxy: "{{ foreman_tftp_proxy | default(ansible_fqdn) }}"
    httpboot_proxy: "{{ foreman_httpboot_proxy | default(ansible_fqdn) }}"
    ipam: 'DHCP'
    domains:
    - "{{ domain_mgmt }}"

# Foreman: operatingsystem
foreman_operatingsystems:
  - name: "CentOS"
    major: "{{ el7_latest | regex_search('CentOS ([0-9]+).([0-9]+)', '\\1') | join }}"
    minor: "{{ el7_latest | regex_search('CentOS ([0-9]+).([0-9]+)', '\\2') | join }}"
    os_family: "Redhat"
    password_hash: "SHA512"
    architectures: 'x86_64'
    media: 'CentOS NREC mirror'
    ptables:
      - "{{foreman_template_prefix }}Kickstart default"
  - name: "AlmaLinux"
    major: "{{ el8_latest | regex_search('AlmaLinux ([0-9]+).([0-9]+)', '\\1') | join }}"
    minor: "{{ el8_latest | regex_search('AlmaLinux ([0-9]+).([0-9]+)', '\\2') | join }}"
    os_family: "Redhat"
    password_hash: "SHA512"
    architectures: 'x86_64'
    media: 'AlmaLinux NREC mirror'
    ptables:
      - "{{foreman_template_prefix }}Kickstart default"
      - "{{foreman_template_prefix }}Kickstart default uefi"

# Foreman: operatingsystem default templates
foreman_os_default_templates:
  - CentOS-provision:
    template_kind: "provision"
    provisioning_template: "{{ foreman_template_prefix }}Kickstart default"
    operatingsystem: "{{ el7_latest }}"
  - CentOS-PXELinux:
    template_kind: "PXELinux"
    provisioning_template: "{{ foreman_template_prefix }}Kickstart default PXELinux"
    operatingsystem: "{{ el7_latest }}"
  - CentOS-PXEGrub2:
    template_kind: "PXEGrub2"
    provisioning_template: "{{ foreman_template_prefix }}Kickstart default PXEGrub2"
    operatingsystem: "{{ el7_latest }}"
  - Almalinux-provision:
    template_kind: "provision"
    provisioning_template: "{{ foreman_template_prefix }}Kickstart default"
    operatingsystem: "{{ el8_latest }}"
  - Almalinux-PXELinux:
    template_kind: "PXELinux"
    provisioning_template: "{{ foreman_template_prefix }}Kickstart default PXELinux"
    operatingsystem: "{{ el8_latest }}"
  - Almalinux-PXEGrub2:
    template_kind: "PXEGrub2"
    provisioning_template: "{{ foreman_template_prefix }}Kickstart default PXEGrub2"
    operatingsystem: "{{ el8_latest }}"

# Foreman hostgroups
foreman_hostgroups:
  - name: "el7"
    architecture: "x86_64"
    operatingsystem: "{{ el7_latest }}"
    medium: "CentOS NREC mirror"
    ptable: "{{foreman_template_prefix }}Kickstart default"
    subnet: "{{ location }}"
    domain: "{{ domain_mgmt }}"
    pxe_loader: "PXELinux BIOS"
    puppet_ca_proxy: "{{ foreman_puppet_ca_proxy | default(ansible_fqdn) }}"
  - name: "el8"
    architecture: "x86_64"
    operatingsystem: "{{ el8_latest }}"
    medium: "AlmaLinux NREC mirror"
    ptable: "{{foreman_template_prefix }}Kickstart default"
    subnet: "{{ location }}"
    domain: "{{ domain_mgmt }}"
    pxe_loader: "PXELinux BIOS"
    puppet_ca_proxy: "{{ foreman_puppet_ca_proxy | default(ansible_fqdn) }}"
  - name: "legacy"
    parent: "el8"
    parameters:
      - name: "biosdevname"
        value: 1
      - name: "installdevice"
        value: "sda"
  - name: "uefi"
    parent: "el8"
    ptable: "{{foreman_template_prefix }}Kickstart default uefi"
    pxe_loader: "Grub2 UEFI"
    parameters:
      - name: "biosdevname"
        value: 1
      - name: "installdevice"
        value: "sda"

# puppet environments
foreman_puppet_environments:
  - name: "production"
  - name: "admin"
  - name: "ussuri"

# Compute profiles
foreman_compute_profile:
  - name: small
    vm_attrs:
      cores:   '1'
      memory: '2254857830' #2.1 GB for el8.6
      interfaces_attributes:
        '0':
          bridge: br0
          model:  'virtio'
          type:   'bridge'
        'br1':
          bridge: br1
          model:  'virtio'
          type:   'bridge'
      volumes_attributes:
        '0':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
  - name: medium
    vm_attrs:
      cores:   '1'
      memory: '4294967296'
      interfaces_attributes:
        '0':
          bridge: br0
          model:  'virtio'
          type:   'bridge'
        'br1':
          bridge: br1
          model:  'virtio'
          type:   'bridge'
      volumes_attributes:
        '0':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
  - name: large
    vm_attrs:
      cores:   '2'
      memory: '4294967296'
      interfaces_attributes:
        '0':
          bridge: br0
          model:  'virtio'
          type:   'bridge'
        'br1':
          bridge: br1
          model:  'virtio'
          type:   'bridge'
      volumes_attributes:
        '0':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
  - name: xlarge
    vm_attrs:
      cores:   '2'
      memory: '8589934592'
      interfaces_attributes:
        '0':
          bridge: br0
          model:  'virtio'
          type:   'bridge'
        'br1':
          bridge: br1
          model:  'virtio'
          type:   'bridge'
      volumes_attributes:
        '0':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
  - name: 2xlarge
    vm_attrs:
      cores:   '4'
      memory: '8589934592'
      interfaces_attributes:
        '0':
          bridge: br0
          model:  'virtio'
          type:   'bridge'
        'br1':
          bridge: br1
          model:  'virtio'
          type:   'bridge'
      volumes_attributes:
        '0':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '10G'
          format_type:  'qcow2'
