---
# Dynamic vars
mgmt_network_cidr: "{{ansible_facts[mgmt_interface]['ipv4']['network']}}/{{ansible_facts[mgmt_interface]['ipv4']['prefix']}}"

# default mgmt gw is proxy-02
foreman_subnet_gateway: "{{  mgmt_network_cidr | ansible.utils.ipaddr('97') | ansible.utils.ipaddr('address') }}"

# default repo env
repo_env: 'prod'

# latest os versions (override in group_vars/<loc>.yaml if needed)
el7_latest: "CentOS 7.9"
el8_latest: "AlmaLinux 8.9"

# default compute resource, overide in group_vars/<location>.yaml
foreman_compute_resource:
  - name: "{{ location }}-controller-01.{{ domain_mgmt }}"
